# POSTGRES DB INFO
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://uahage2.c7qbk7qns6ot.ap-northeast-2.rds.amazonaws.com:5432/jpa_study
    username: postgres
    password: hohocom!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create